services:
  - type: web
    name: jassi-tts-api
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt -r requirements-xtts.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.20
      - key: TTS_ENGINE
        value: xtts
      - key: COQUI_TOS_AGREED
        value: "1"
      - key: DEFAULT_LANGUAGE
        value: en
      - key: MAX_TEXT_CHARS
        value: "1200"
      - key: XTTS_MODEL_NAME
        value: tts_models/multilingual/multi-dataset/xtts_v2
      - key: JASSI_VOICE_PATH
        value: /etc/secrets/voice_preview_jassi.mp3
      - key: API_KEY
        sync: false
